package com.example.spendolive.Expense.domain;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ExpenseDTO {

    private Long expenseId;
    private Long memberId;
    private Long categoryId;

    private String categoryName;
    private String expenseType;

    private String expenseTitle;
    private Integer amount;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date expenseDate;

    private String paymentMethod;
    private String memo;

    private String repeatYn;
    private String repeatCycle;
    private String fixedYn;

    private String autoGeneratedYn;

    private Date createdAt;
    private Date updatedAt;
}