spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=system
spring.datasource.password=1234

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
#  이메일 인증 API코드
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# 465 SSL 전용 소켓 팩토리 강제 지정 (★타임아웃 해결의 핵심)
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

# 타임아웃 시간 여유 부여
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
# 카카오 
kakao.client.id=api
kakao.redirect.uri=http://localhost:8080/member/kakaoCallback.do
# 오픈뱅킹
openbanking.client-id=api
openbanking.client-secret=api
openbanking.redirect-uri=http://localhost:8080/member/openBankingcallback.do
# 이용기관코드 (10자리)
openbanking.useorg-code=code
# 돈이 최종적으로 들어올 내 서비스의 수납 계좌 정보
openbanking.cntr-bank-code=002
openbanking.cntr-account-num=12345678901234
openbanking.cntr-account-holder=스펜드올리브