spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=system
spring.datasource.password=1234

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
#  이메일 인증 API코드
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chung100302@gmail.com
spring.mail.password=fyejcecmlfmkjwzn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
# 카카오 
kakao.client.id=c349fc4dab654ed62fc3ee520b6215c6
kakao.redirect.uri=http://localhost:8080/member/kakaoCallback.do
kakao.javascript.key=a4ad12d708f8e69db188781efdf8d0d8
# 오픈뱅킹
openbanking.client-id=73d481d1-add3-4fef-b002-091aa3547cbb
openbanking.client-secret=014fd913-1678-4dd6-9a30-f0a9193e48d4
openbanking.redirect-uri=http://localhost:8080/member/openBankingcallback.do
openbanking.integrated-redirect-uri=http://localhost:8080/member/openBankingIntegratedcallback.do
openbanking.code=M202601673
# 이용기관코드 (10자리)
openbanking.useorg-code=1101078958
# 돈이 최종적으로 들어올 내 서비스의 수납 계좌 정보
openbanking.cntr-bank-code=002
openbanking.cntr-account-num=12345678901234
openbanking.cntr-account-holder=스펜드올리브
# ==========================================
# 💳 TOSS PAYMENTS CONFIGURATION
# ==========================================
# 프론트엔드(JSP)용 클라이언트 키
toss.client-key=test_ck_yZqmkKeP8gBgMeYDwNpprbQRxB9l
# 백엔드(Java) 통신용 비밀 키
toss.secret-key=test_sk_26DlbXAaV07qYBGmEDen3qY50Q9R

# 형 서버 도메인 주소 (나중에 리눅스 서버 올리면 이것만 도메인으로 바꾸면 됨)
toss.base-url=http://localhost:8080
# solapi 
solapi.api-key=NCS5XQD8USSHHDZ7
solapi.secret-key=9KT7VBBGWLDEQTT8J62HI68M8QC0ERXC

server.servlet.session.timeout=1800s